language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .
  - pip install numpy
  - pip install pytest pytest-cov
  - pip install codecov
  - pip install pylint pycodestyle pydocstyle

script:
  - pytest --cov
  - pylint ./src/dl_with_numpy
  - pycodestyle ./src/dl_with_numpy
  - pydocstyle ./src/dl_with_numpy

after_success:
    codecov

notifications:
    email: never
