language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .
  - pip install numpy
  - pip install pytest pytest-cov
  - pip install codecov

script:
  - pytest --cov=dl_with_numpy tests/

after_success:
    codecov

notifications:
    email: never
